language: clojure
lein: lein2
install:
    - sudo apt-get update
    - sudo apt-get -y install docker
before_script:
    - sudo service docker start
    - docker ps
script: lein do clean, test
notifications:
  email: false