language: clojure
lein: lein2
install:
    - uname -r
    - sudo apt-get update
    - sudo apt-get install linux-image-generic-lts-trusty
    - uname -r
    - which wget
    - wget -qO- https://get.docker.com/
    - docker ps
script: lein do clean, test
notifications:
  email: false