language: clojure
lein: lein2
install:
    - uname -r
    - sudo apt-get update
    - sudo apt-get install linux-image-generic-lts-trusty
    - sudo reboot
    - uname -r
    - which wget
script: lein do clean, test
notifications:
  email: false